Add hardhat project
dianiivanov/evm-bridge pull request #1
Opened 2023-09-12 12:25 UTC by dianiivanov

2023-09-13 07:49 UTC, arrusev requested changes

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +    function claim(IERC20 tokenAddress, uint256 amount) public {
do you need to use IERC20 type here, in case you do not use any of its functionalities?

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +        if (baseToWrappedToken[address(tokenAddress)] == address(0)) {
may be it would be better to declare a new local variable for `baseToWrappedToken[address(tokenAddress)]` value instead of reading the state everytime

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +        releasableFor[msg.sender][tokenAddress] -= amount;
make sure to update the contract state before calling other contracts

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +    function addTokensMapping(
what is this function used for?

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/WrapperToken.sol
> +    function mint(address account, uint256 amount) public {
should everyone be able to mint wrapped tokens?

2023-09-13 07:49 UTC, arrusev commented on evm-bridge/contracts/WrapperToken.sol
> +    function burn(address account, uint256 amount) public {
should everyone be able to burn wrapped tokens?

2023-09-16 08:06 UTC, dianiivanov commented on evm-bridge/contracts/Bridge.sol
> +    function addTokensMapping(
Initially It was public but as I won't maintain the mappings in the source bridge, I dont need this anymore

2023-09-18 06:17 UTC, arrusev requested changes
Almost there, leaving a few tips for improvements

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +        address wrappedToken = baseToWrappedToken[address(tokenAddress)];
You don't have to cast the `tokenAddress` to `address`, it is already an address

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +    //release from the target bridge
The comment is misleading i think, it should be the source bridge, right?

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +error TokenNotMapped(WrapperToken tokenAddress);
What is the purpose of passing `WrapperToken` instead of its address?

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +    function burn(WrapperToken tokenAddress, uint256 amount) public {
IMO it would be more readable if you pass `address` type here and cast it to `WrappedToken` when calling `balanceOf` and `burn`

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +    function lock(IERC20 tokenAddress, uint256 amount) public {
IMO it would be more readable if you pass `address` type here and cast it to `IERC20` when calling `transferFrom`

2023-09-18 06:17 UTC, arrusev commented on evm-bridge/contracts/Bridge.sol
> +        claimableFor[msg.sender][tokenAddress] -= amount;
best practice is to update the state before calling external contracts

2023-09-19 05:32 UTC, arrusev approved these changes

2023-09-19 08:12 UTC, merged